### Copyright (C) 2020 - present Alexander, Matthias, Glynis 
###
### This program is free software: you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program.  If not, see <http://www.gnu.org/licenses/>.

###
### N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
###

@url = https://localhost:3000/graphql
#@url = https://gener-iert-12345.herokuapp.com/graphql

### Neuen Song anlegen
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createSong(
      titel: "Test",
      label: SONY_MUSIC
      produzent: "John Williams",
      interpret: ZUGEZOGENMASKULIN,
      lauflaenge: 2.33,
      erscheinungsdatum: "2020-02-04"
  )
}

### Vorhandenen Song aktualisieren
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateSong(
    _id: "00000000-0000-0000-0000-000000000001",
    titel: "Geaendert",
    label: SONY_MUSIC,
    produzent: "Dieter",
    interpret: ZUGEZOGENMASKULIN,
    lauflaenge: 2.30,
    erscheinungsdatum: "2018-01-31",
    version: 0
  ) {
    version
  }
}

### Vorhandenen Song loeschen
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  deleteSong(id: "00000000-0000-0000-0000-000000000001")
}
